language: java
env:
 - GEM_PATH=
script: mvn install
jdk:
  - oraclejdk7
  - openjdk7
before_script:
  - createuser -U postgres -d -S -R maxcom
  - createuser -U postgres -D -S -R linuxweb
  - createuser -U postgres -D -S -R jamwiki
  - createdb -U maxcom lor
  - psql -f sql/demo.db -U maxcom lor
  - psql -c 'create extension hstore;' -U postgres lor
before_install:
  - mvn -T 2C dependency:go-offline
